#define CONFIG_FIRMWARE_VERSION "v1.3"

#define CONFIG_FIRMWARE_NAME "RubLogin"

#define CONFIG_MDNS_HOSTNAME "rublogin"

#define CONFIG_ACCESSPOINT_SSID "RubLogin_AP"

#define CONFIG_LOGOUT_PERIOD_START_HOUR 6
#define CONFIG_LOGOUT_PERIOD_START_MINUTE 50

#define CONFIG_LOGOUT_PERIOD_END_HOUR 7
#define CONFIG_LOGOUT_PERIOD_END_MINUTE 10

#define CONFIG_LOGIN_ROUTINE_IN_LOGOUT_PERIOD_INTERVAL_MS 20000

#define CONFIG_PERIODIC_ROUTINE_INTERVAL_MS 600000
#define CONFIG_DEEPSLEEP 1
#define CONFIG_DEEPSLEEP_DURATION_MS 60e3 * 10
#define CONFIG_DEEPSLEEP_INTERVAL_MS 60000

#define CONFIG_PING_ADDRESS "www.google.com"
#define CONFIG_NTP_POOL "de.pool.ntp.org"

